language: rust
rust:
  - nightly
cache: cargo
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libopenal-dev libsndfile1-dev
before_script:
  - rustup component add rustfmt-preview
script:
  - cargo fmt -- --write-mode=diff
  - cargo build -p timbre
  - cargo test -p timbre
notifications:
  email: false
