[package]
name = "timbre"
version = "0.1.0"
authors = ["Aleksey Ivanov <ialexxei@gmail.com>"]

[dependencies]
lazy_static = "1.0.0"
ears = "0.4.0"
rand = "0.4.1"
serde = "1.0.26"
serde_derive = "1.0.26"
toml = "0.4.5"
