[package]
name = "timbre-gtk"
version = "0.1.0"
authors = ["Aleksey Ivanov <ialexxei@gmail.com>"]

[dependencies]
gio = "0.3.0"
diesel = { version = "1.1.1", features = ["sqlite"] }

[dependencies.gtk]
features = ["v3_18"]
version = "0.3.0"

[dependencies.timbre]
path = "../timbre"
